Dev to Master, v0.2.3
saucelabs/foxdriver pull request #16
Opened 2019-12-03 09:39 UTC by benmalka

- Support -P option
- Hardkill in Windows (In case the process isn't being closed)
- Handle long post data
- Event-based console API
- Enable cookie extraction
- Fix Documentation
- Fix bugs in the new features

2020-09-07 13:21 UTC, christian-bromann requested changes
@benmalka these changes look great but it seems that you have pushed them to your own fork. Would you mind to clean up the PR (revert changes to e.g. the package name `@benmalka/foxdriver`) and have these merged upstream?

2020-09-07 13:21 UTC, christian-bromann commented on README.md
> -Foxdriver [![Build Status](https://travis-ci.com/saucelabs/foxdriver.svg?token=px5tFzamGvYgujeyYVEp&branch=master)](https://travis-ci.com/saucelabs/foxdriver)
It would be good if we could keep the badge

2020-11-28 18:35 UTC, benmalka commented
As you can see there are tons of changes since I've forked this project. How would you like to address all of them?

2021-02-01 22:09 UTC, christian-bromann commented
> How would you like to address all of them?

@benmalka is there a way we can address conflicts and get this merged?

2021-02-02 08:51 UTC, benmalka commented
@christian-bromann I've opened a new PR #22

2021-02-02 08:51 UTC, closed without merging